# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfjm1A0XjkkQbrEBcEL6Cfl1QhFPpN5z
"""

import matplotlib.pyplot as plt
import numpy as np

def QTWM(t,a,b,c):
  return (a*t**2+b*(t+c))
hc_a=1.0
hc_b=-2.5
hc_c=3.5
g_values=np.linspace(0,1,100)
hc_temp=QTWM(g_values,hc_a,hc_b,hc_c)
plt.plot(g_values,hc_temp,label="Hardcoded:a={hc_a},b={hc_b},c={hc_c}")
sets=int(input("Enter number of sets:"))
coefficients=[]
for i in range(sets):
  a=float(input("Enter coefficient a:"))
  b=float(input("Enter coefficient b:"))
  c=float(input("Enter coefficient c:"))
  coefficients.append([a,b,c])
for i,(a,b,c) in enumerate(coefficients):
  Temperature=QTWM(g_values,a,b,c)
  plt.plot(g_values,Temperature,label=f"Set {i+1}:a={a},b={b},c={c}")
plt.xlabel("Time")
plt.ylabel("Temperature")
plt.legend()
plt.show()